### ISSUE TITLE
Does not launch after the new update

### ISSUE THREAD

**Issue by ar0ra1** [Alecaddd/sequeler#49] opened 2017-10-24 03:00 UTC
`$ com.github.alecaddd.sequeler `
>[INFO 08:29:36.999537] Application.vala:153: Sequeler version: 0.3.4
[INFO 08:29:36.999609] Application.vala:155: Kernel version: 4.10.0-37-generic
[ERROR 08:29:37.063142] [GLib-GIO] Settings schema 'com.github.alecaddd.sequeler' does not contain a key named 'tot-connections'
Trace/breakpoint trap (core dumped)

**Comment by Alecaddd** [comment] 2017-10-24 03:06
Yup, I'm an idiot!
I just published an update to fix my mistake, waiting for it to be released on the AppCenter.
Closing because duplicate of #48

**Closed** 2017-10-24 03:06 UTC

**Comment by ar0ra1** [comment] 2017-10-24 03:13
My bad didn't see the closed section
