### ISSUE TITLE
PSQL table names don't show

### ISSUE THREAD

**Issue by Janiczek** [Alecaddd/sequeler#62] opened 2017-12-01 08:24 UTC
![tables](https://user-images.githubusercontent.com/149425/33474080-4f00fff4-d679-11e7-9cb1-99c4669acea6.png)

The tables on the left should have been something like `person`, `company`, ... but instead are all `crm`.

Let me know if I can give any additional info or help somehow!

Version: `0.4.0`

**Comment by Alecaddd** [comment] 2017-12-01 10:41
Closing because duplicate of #52

**Closed** 2017-12-01 10:41 UTC
