### ISSUE TITLE
Error when closing program run from terminal

### ISSUE THREAD

**Issue by svartrev** [Alecaddd/sequeler#235] opened 2019-03-09 13:34 UTC
When running the application from the terminal, when closing the application, I get the following error message:
`(Sequeler:21102): Gtk-CRITICAL **: 15:29:13.464: gtk_main_quit: assertion 'main_loops != NULL' failed`

This happens even if I do nothing but run the program and immediately close it.

**Comment by Alecaddd** [comment] 2019-03-12 05:06
This is normal for a GTK application triggering the `Gtk.main_quit ()` to close any ongoing interaction with the `MainLoop ()`.
Sequeler leverages a lot of async methods and sometimes it taps the `MainLoop ()`.
That error is common when closing the app from terminal and it's not a bug.

**Closed by Alecaddd** 2019-03-12 05:06 UTC
Labels: invalid
