### ISSUE TITLE
Connect to DB with SSH

### ISSUE THREAD

**Issue by vk2r** [Alecaddd/sequeler#33] opened 2017-10-12 09:52 UTC
I don't know if it's implemented.
If so, how do I do it ?

**Comment by Alecaddd** [comment] 2017-10-12 16:33
Not implemented yet.
It's a feature I'll probably add for version 1.0.0
Thanks for the request

**Comment by num3thod** [comment] 2017-12-01 03:57
Seconded. Would also love to see this feature in 1.0

Also, happy to help test and whatnot.

**Comment by nesslopz** [comment] 2018-02-25 23:05
Use LocalForward when connecting with SSH.
eg: 2000 > 3306

Then you can connect with 127.0.0.1 on port 2000

**Comment by nmunro** [comment] 2018-05-03 11:30
nesslopz Could you elaborate exactly how you did this?

**Comment by divoxx** [comment] 2018-05-16 22:31
Also, it would be nice if it could leverage the running ssh-agent rather. That way, the application itself does not need to handle keys and passphrases, etc.

**Comment by nesslopz** [comment] 2018-05-18 02:50
I'm sorry for late.
as @divoxx said, the command is:
`ssh -L 9000:localhost:3306 user@SERVER_IP`

then connect to Sequeler with port 9000

The easiest way to do this is using config ssh file
`nano ~/.ssh/config`

Host **my_server_name**
   HostName xxx.xxx.xx.xxx
   User **myuser**
   LocalForward 9000 127.0.0.1:3306
   IdentityFile ~/.ssh/id_rsa

Replace: my_server_name with a custom name for server, eg: prod
xxx.xxx.xx.xxx is server IP or dns
myuser is user on server, eg: root
in LocalForward you choose ports, first is localhost port and 3306 is server default mysql port
IdentityFile is id_rsa location, try to add ssh key on server first for no need passwords

Then just run:
`ssh my_server_name`

(Sorry for my bad english)

**Comment by Alecaddd** [comment] 2018-10-31 01:52
It's bee a while, but I've been finally started working on this feature and it will be available in the next version of Sequeler 😊

**Comment by Alecaddd** [comment] 2018-11-02 05:12
I'm implementing something like this.

![ssh](https://user-images.githubusercontent.com/2527103/47894987-1efe3d00-de23-11e8-9f03-d0899943bc90.png)

**Comment by num3thod** [comment] 2018-11-02 12:40
Nice! I'm imagining that it will rely on ssh-agent to provide the correct pub key?

**Comment by Alecaddd** [comment] 2018-11-02 18:00
@num3thod that's correct. I'm automatically detecting if the user already has an SSH key available. If not, a warning message will appear in the dialog with a link to the GitHub guide to generate one.
No need to input the SSH key manually or store anything inside Sequeler. :blush:

**Comment by Alecaddd** [comment] 2018-11-06 08:32
More progress for this feature.
If you try to activate the SSH tunneling without having a pub key file, the fields won't appear and a little warning will let the user know and redirect him to the GitHub tutorial to generate one.

![dialog-warning](https://user-images.githubusercontent.com/2527103/48051913-4de61d00-e15b-11e8-901d-3c06601adb42.png)

**Comment by jhit** [comment] 2018-11-12 12:19
> @num3thod that's correct. I'm automatically detecting if the user already has an SSH key available. If not, a warning message will appear in the dialog with a link to the GitHub guide to generate one.
> No need to input the SSH key manually or store anything inside Sequeler.

That will be a issue for many people. It is common practice to not use your primary private key (id_rsa) for everything. I have different keys for example github.com and my private server with different names. I store those keys in keepassxc which acts as a ssh-agent.

Normally ssh automatically checks for keys stored in the ssh-agent, so nothing to configure here. If ssh-agent is not running (you can check the socket that is defined in the env variable $SSH_AUTH_SOCK) you could try to use the local private key (~/.ssh/id_rsa)

**Comment by Alecaddd** [comment] 2018-11-12 18:02
@jhit that's a really good point, thanks for raising the issue.
I also got another couple of feedback regarding users having some specific scenarios where they connect via password login and not via ssh key.
I think I need to restructure the connection dialog in order to let the user pick whichever option he wants and avoid for the code to get too convoluted trying to identify the proper method.

**Comment by albfan** [comment] 2018-11-21 09:52
A side project to translate a working c example into vala

https://gitlab.gnome.org/albfan/ssh-vala-examples

tunnel is still not working:

https://gitlab.gnome.org/albfan/ssh-vala-examples/issues/1

once fixed there it should be fairly easy to port here

**Comment by Alecaddd** [comment] 2018-11-21 18:02
@albfan Thank you so much for your help in this.
I was trying to port it too but I'm still not able to make the tunnel work.
It seems like it hangs when running `listener.accept()`

I hope you'll be able to figure it out, that'd be huge for Sequeler 😄

**Comment by Alecaddd** [comment] 2018-11-22 18:52
@albfan Thank you so much, this is amazing!

I'm having issues in reworking your example into Sequeler. Specifically, I'm trying to make it run inside an async method that yields to the parent once the tunnel is open, but then it must regain control if the tunnel closes.

Would you be able to fork the `dev` branch and take a look at the `ConnectionManager.vala` file?

**Comment by albfan** [comment] 2018-11-23 05:11
Sure, let me check it

**Comment by Alecaddd** [comment] 2018-11-23 23:51
Ah damn, I forgot to push.
I'm gonna try to clean up the code a bit to make it saner and push to dev.

**Comment by albfan** [comment] 2018-11-24 09:57
@Alecaddd Good news!. I fixed vala ssh tunnel example

See https://gitlab.gnome.org/albfan/ssh-vala-examples/issues/2#note_371620 and https://gitlab.gnome.org/albfan/ssh-vala-examples/commit/dfa3718d71e6b33d9f1e08a08d83cf789a81009b

I successfully test it with sequeler:

```
systemctl start mariadb
systemctl start sshd
git clone https://gitlab.gnome.org/albfan/ssh-vala-examples
cd ssh-vala-examples
./libssh2-tunnel-example 127.0.0.1 user password 127.0.0.1 4000 127.0.0.1 3306
cd ..
git clone https://github.com/Alecaddd/sequeler
git checkout dev
```

go to Builder, open sequeler project an run (we need to clone outside Builder as it still do not manage git, so it cannot change to other branch

I can connect database through port 3306 or 4000

@Alecaddd take a look at my implementation on ssh-vala-examples, maybe you can figure out how to fix it:

https://gitlab.gnome.org/albfan/ssh-vala-examples/blob/master/test-libssh2-tunnel.vala

Will check later if you did it, if not, I'll try to review ssh tunneling implementation on sequeler and provide a MR.

About segfault, although I think it is easily reproducible, the stacktrace running under gdb could be interesting ¿can you paste output here too?

**Comment by albfan** [comment] 2018-11-24 23:33
@Alecaddd 

On #173 I basically implemented all needs for ssh tunneling

1. `listener.accept()` is a blocking operation, so you cannot launch test_connection or init_connection there (that's why launching different programs just works) The proper way would be to emit a signal when tunneling is setup. I just worked around waiting 3 seconds for that to be configured on async open_ssh_connection()
2. Fixed buffered tunneling write
3. Make ssh public key entry passwor type
4. Forward to db port (another workaround as it can be not configured and you should relay on default port for selected database)
5. segfault was related to try to read "db_port" instead of "port"
6. See ssh host shouldn't be the same as forwarded host (tried to add a TODO to warn about that)
7. Take care of height of connection dialog, for me is taller that my screen height

test_connection works this way, but connection, after succesful connect is closed (that's why this is a WIP)

I tried to split changes into atomic meaningful changes. I see you get progress on dev branch so try to rework this on top of it.

**Comment by Alecaddd** [comment] 2018-11-25 18:59
Thank you so much for all your hard work, this is looking great.
I fixed the conflicts and merged to `dev`.

I also put back the `begin ()` call for the async methods. Was there any specific reason for removing those?

I'm testing the `test_connection` with my remote VPS but it keeps failing right after `Waiting for remote connection`.
Also, if I test it again I get the output `Unable to create Port Forwarding`

**Comment by albfan** [comment] 2018-11-26 07:35
About `begin` (my mistake)

About `test_connection` I think you should apply #174

About open_connection I think it needs to be called async as on `ssh_tunnel_ready` signal it needs to start opening connection while ssh_tunnel goes to listener.accept()

About https://github.com/Alecaddd/sequeler/blob/dev/src/Services/ConnectionManager.vala#L126
Don't see why it should get the data["port"] if set, as this is the forwarded port. this should be 0 so tunnel get first avaliable free port, and that port number should be passed to create connection string

Remember here https://github.com/Alecaddd/sequeler/blob/dev/src/Services/ConnectionManager.vala#L207 default port should be get from configured Service Type. I suppose that needs a method in DataBaseType `has_port()` to know if that Type can use tunnel, and retrieve default port from `db_type`

**Comment by albfan** [comment] 2018-11-26 20:14
As expected, making init_connection async it works. But ssh tunnel is closed after that first communication.

https://github.com/Alecaddd/sequeler/pull/174/commits/1f4a35bf8dd84a1ba3f395a4596c5aa34582deee

tunnel should be keep alive as long as connection is open

**Comment by albfan** [comment] 2018-11-26 20:40
With 3419467 tunnel is keep alive while a real connection is in use.

I think a signal on connection close and connect that to ssh_tunnel_close will be a much maintanable code, but all plumbings are in place now.

Time to polish, squash and refactor!

**Comment by Alecaddd** [comment] 2018-11-26 21:35
Still not working for me.
This is the full debug trace and output I get when trying to test the connection:
![screenshot from 2018-11-26 13-31-02](https://user-images.githubusercontent.com/2527103/49043361-b08d7000-f17f-11e8-9021-25ebb5726078.png)

And if I trigger again the test connection, the result message is not updated properly with the error output.
![screenshot from 2018-11-26 13-31-15](https://user-images.githubusercontent.com/2527103/49043403-cef36b80-f17f-11e8-87a5-0b823843d329.png)

I saw you comment out all the `throw new Error` and adding a return instead. Could you elaborate on that? I'd like to understand the reasoning why and how this affects the user-facing response message.

Thanks again for this massively helpful contribution.

**Comment by albfan** [comment] 2018-11-26 23:22
See point 6 on https://github.com/Alecaddd/sequeler/issues/33#issuecomment-441403607. There're two host involved on ssh tunneling. SSH host is where you connect to by ssh. Then there's a host reachable from that SSH host where you forward connection.

I'm using 127.0.0.1, so:

    local ---> 127.0.0.1:22 --> 127.0.0.1:3306
             <-- 127.0.0.1:9000 <--

But for your host there's no 204.44.81.194 reachable from your SSH Host 204.44.81.194

You can read about it on https://blog.trackets.com/2014/05/17/ssh-tunnel-local-and-remote-port-forwarding-explained-with-examples.html

You need to add another entry for that second host. Let me rework that on #174 PR

About removing Errors, just trying to simplify things while debugging as I get some fatal errors that breaks the app, they should be cached and controlled (for example if port is already used)

**Comment by albfan** [comment] 2018-11-26 23:43
Opps, no. forwarded port is configured on entry field "Host", did you merge #174?

**Comment by Alecaddd** [comment] 2018-11-26 23:53
I didn't merge yet as it wasn't working and I was waiting for your answer about the errors 😄 

So, when I do this in the terminal:
```
ssh -L 9000:localhost:3306 ubuntu@204.44.81.194
```
I get a working forwarded port where I can connect to my Database on my remote SSH host via my local port 9000, correct?

In reality, in sequeler, I should have a third host, something like `127.0.0.1` to use a bridge between my localhost and my 204.44.81.194 remote server?

**Comment by albfan** [comment] 2018-11-27 00:59
with merge I mean trying locally. I have no external server to try your use case.

About your ssh command, what libssh2 is creating is:

    ssh -L 9000:127.0.0.1:3306 ubuntu@204.44.81.194

so you need to check what ip localhost is resolving on your server ubuntu@204.44.81.194

About "third host", ssh tunnel is using 127.0.0.1 with flag `-L` so as shown on debug messages:

> HOST=127.0.0.1;PORT=9000

should be enough

**Comment by Alecaddd** [comment] 2018-11-27 01:07
Yes, I pulled your PR and built it locally, still not working for me.
I sent you an invite to my Slack channel, if you jump on that I can add your SSH key to my test server so you can use it to test a remote VPS connection.

**Comment by Alecaddd** [comment] 2018-11-27 06:08
I set the `bind-address` to `0.0.0.0` in order to accept remote connections and restarted the service.

**Comment by albfan** [comment] 2018-11-27 08:53
Definitely there's something wrong with ssh tunnel implementation as

    ssh -L 9000:127.0.0.1:3306 ubuntu@204.44.81.194

works, but:

    ./test-libssh2-tunnel 204.44.81.194 ubuntu <public_key_password> 127.0.0.1 3306 127.0.0.1 9000

doesn't work. 

if I check the implementation of test-libssh2-tunnel.vala it should be:

    ./test-libssh2-tunnel 204.44.81.194 ubuntu <public_key_password> 127.0.0.1 9000 127.0.0.1 3306

but that leads to:

    Nov 27 08:31:24 blog sshd[32695]: error: bind: Address already in use
    Nov 27 08:31:24 blog sshd[32695]: error: channel_setup_fwd_listener_tcpip: cannot listen to port: 3306

I can reproduce with my sshd and mariadb.service, so it this works for my usecase as I was using always localhost, and implementation doesn't matter, but that implementation is a reverse ssh tunnel as this blog post confirm:

https://marianafranco.github.io/2017/03/10/libssh2-tunnel/

So we just need to implement the ssh local tunnel to make it work which I think is implemented here:

https://github.com/libssh2/libssh2/blob/master/example/tcpip-forward.c

**Comment by albfan** [comment] 2018-11-27 21:59
ehh, well the correct example is https://github.com/libssh2/libssh2/blob/master/example/direct_tcpip.c

So just need to turn our remote tunnel into local tunnel, and it should just work.

**Comment by albfan** [comment] 2018-11-28 07:42
I just updated https://gitlab.gnome.org/albfan/ssh-vala-examples with direct tunnel

https://gitlab.gnome.org/albfan/ssh-vala-examples/commit/65039f183eb9b7b0f3b654775dc21dd24e22cc85

So good part of using Maria Franco implementation is that ssh2 examples are designed as a one shot. And they closed as soon as data ends. The vala implementation is listening forever.

So this only takes to migrate https://gitlab.gnome.org/albfan/ssh-vala-examples/blob/master/test-libssh2-direct-tunnel.vala here

**Comment by Alecaddd** [comment] 2018-12-03 00:44
I started to rework your example into Sequeler, but I can't seem to be able to use the `Linux` package.
I downloaded the vapi but I can't find the package to install and how to properly update the meson dependencies.

**Comment by Alecaddd** [comment] 2018-12-03 01:42
Nevermind, I had to tell meson to manually get the package:
`linux_dep = meson.get_compiler('vala').find_library('linux')`

**Comment by albfan** [comment] 2018-12-03 16:15
Nice. Update branch and I would take a look again

**Comment by Alecaddd** [comment] 2018-12-15 22:07
Ok, I merged the code and updated it a bit to tackle these issues I was having:
* Unable to test the connection more than once
* Closing the dialog while the connection was being tested prevented further tests

On real connection, the UI freezes and I've been trying to troubleshoot that without luck.
I started a small refactor to convert all the UI related methods to `async` methods.

Another issue, which I can't really figure out, is that the app crashes randomly sometimes with a segfault error. I suspect is because of the multiple calls happening on session closing.

Anyway, I pushed everything to the `dev` branch and leave it there for now.
I'll probably get back to this after the holidays, so, if anyone wants to give it a try, good luck :smile:

**Comment by Alecaddd** [comment] 2018-12-16 01:05
I lied, I didn't stop working on this.
So, I was able to fix the random crashes happening during `test_connection` and properly open a real connection from the dialog, yay!

The problem is the `database_schema.reload_schema ();` which fetches the schema and full list of tables to populate the sidebar. Since this is a sync method, the UI freezes or the app simply crashes.
Refactoring all the data handling methods to async methods should fix this last problem.

Also, if I open the connection without triggering the reload_schema, and then I click on the reload button at the bottom of the sidebar to manually trigger the reload schema, that works and doesn't cause a crash.

**Comment by albfan** [comment] 2018-12-16 03:50
Threads all around! Nice to see you get progress on these.

Triaging multithreading is hard on vala so this one is a great one to check

**Comment by Alecaddd** [comment] 2018-12-21 22:01
Ok, I pushed an update to the `dev` branch with everything working for me.

✅ Testing and Connecting from the `ConnectionDialog` works!
✅ Connecting from the sidebar library works
✅ Disconnecting and reconnecting to an SSH or non-SSH connection works

What doesn't currently work/crashes

❌ Changing database schema from the dropdown once inside an open SSH connection (working on that to fix it)
❌ Connecting and disconnecting really quickly between multiple connections causes the app to crash around the 6th or 7th triggered connection (Potentially, we could ignore this for now as it's a really unusual behavior I'm not expecting anyone to have)

Things that need to be improved

* Have a spinner/loader indicator when loading content/data
* Refactor fetching methods to async threads to avoid UI freezes when in SSH connection

We're getting so close 😅

**Comment by Alecaddd** [comment] 2018-12-22 02:38
With the latest commit to `dev`, I was able to fix the segfault when changing database schema from an opened connection dropdown.
Yay!

I'm gonna start refactoring methods to not sue the `MainLoop` and properly turn UI related methods into async methods to speed up the app and avoid freezes.

**Comment by albfan** [comment] 2018-12-22 09:49
Not sure about this commit 6a05ee8. I just reverted and everything is working for me.

About ssh tunnel not closed after logout, I found that `connection_manager` passed to `init_connection()` is done by value, so `ssh_tunnel_close()` only set `ssh_tunnel_alive` for that `connection_manager` instance so other `connection_managers` keep tunnel alive. This only happens when you reload schemas:

1. Open a connection
2. Reload schema
3. logout

just added this debug to see connection_manager instances d6dd846

Running with G_MESSAGES_DEBUG=all you will see something like:

```
** (Sequeler:28501): DEBUG: 10:47:20.735: Main.vala:92: connection manager 0x563091aadad0
** (Sequeler:28501): DEBUG: 10:47:20.735: ConnectionManager.vala:382: closing ssh tunnel from: Main.vala:93 0x5630914e64c0
** (Sequeler:28501): DEBUG: 10:47:20.735: ConnectionManager.vala:328: The client at 127.0.0.1:9000 disconnected!
** (Sequeler:28501): DEBUG: 10:47:20.735: ConnectionManager.vala:329: connection manager 0x563091aa4890
** (Sequeler:28501): DEBUG: 10:47:20.926: ConnectionManager.vala:281: Waiting for remote connection 0x7f1888018e30
```

**Comment by Alecaddd** [comment] 2018-12-27 05:44
I think I fixed everything!!!

Now I'm able to change database, reload schema, log out, and log back in again without crashes or warnings.
Whenever you can, give it a spin and let me know if you see something weird.

Next on the list is concluding the refactoring of all the data fetch methods to speed up the app during ssh tunneling, and if we don't encounter any other weird crashes, a shiny new release can be drafted 😄

**Closed** 2018-12-30 02:13 UTC
Labels: enhancement, help wanted
