### ISSUE TITLE
AWESOME WORK - Suggestion

### ISSUE THREAD

**Issue by leonbollerup** [Alecaddd/sequeler#289] opened 2019-11-12 08:11 UTC
Hi there,

Awesome work - i asume you are using https://www.sequelpro.com/ as a inspiration.

As a recent migrate from macOS to ChromeOS (with crostini) i love what you are doing here - is there any plans to add support for editing without writing complicated SQL queries?

**Comment by Alecaddd** [comment] 2019-11-17 06:42
Yup, this type of implementation is on its way.
Duplicate of Bug #260

**Closed by Alecaddd** 2019-11-17 06:42 UTC
