### ISSUE TITLE
Application crash when trying to display content of a table that contains json field

### ISSUE THREAD

**Issue by isneezy** [Alecaddd/sequeler#265] opened 2019-06-28 10:50 UTC
When I try to view contents of a table with json field the application crashes with the following output:
```
** (Sequeler:21510): W

ARNING **: 12:34:22.852: Invalid column bind data type. 245


(Sequeler:21510): GLib-WARNING **: 12:34:22.862: GError set over the top of a previous GError or uninitialized memory.
This indicates a bug in someone's code. You must ensure an error is NULL before it's set.
The overwriting error message was: Invalid column bind data type. 245


(Sequeler:21510): GLib-GObject-CRITICAL **: 12:34:22.863: g_strdup_value_contents: assertion 'G_IS_VALUE (value)' failed
Segmentation fault
```

Here is the dump of the table:
```sql
-- MySQL dump 10.13  Distrib 5.7.25, for Linux (x86_64)
--
-- Host: localhost    Database: homestead
-- ------------------------------------------------------
-- Server version	5.7.25

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Table structure for table `customers`
--

DROP TABLE IF EXISTS `customers`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `customers` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `first_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `last_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `phone` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `email` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `avatar` longtext COLLATE utf8mb4_unicode_ci,
  `address` json DEFAULT NULL,
  `store_id` bigint(20) unsigned NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `customers_store_id_foreign` (`store_id`),
  CONSTRAINT `customers_store_id_foreign` FOREIGN KEY (`store_id`) REFERENCES `stores` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `customers`
--

LOCK TABLES `customers` WRITE;
/*!40000 ALTER TABLE `customers` DISABLE KEYS */;
INSERT INTO `customers` VALUES (1,'Ivan','Vilanculo','+258841234567','ivanvilanculo@gmail.com','https://ivan.vilanculo.me/public/img/profile-pic.png','{\"city\": \"Hildaside\", \"state\": \"North Dorthymouth\", \"suite\": \"918\", \"address\": \"65239 Gaston Squares\\nIciechester, MT 26490\", \"postcode\": \"00454\"}',1,'2019-06-28 09:50:08','2019-06-28 09:50:08'),(2,'Adelino','Ngomacha','807-696-4706 x6135','lesly31@ebert.com','https://scontent.fmpm2-1.fna.fbcdn.net/v/t1.0-9/18010335_1368479143198750_8224272290403955990_n.jpg?_nc_cat=100&_nc_oc=AQnkM9kvMWpwDYHup5XR3yhoTWZ0FZnoDFz4Dgtz6Bkp9byaootpoL2k0SlpaXKxl9U&_nc_ht=scontent.fmpm2-1.fna&oh=203cc6a6b83d900e2fea9890090d2683&oe=5D907F2A','{\"city\": \"New Marieland\", \"state\": \"Framiton\", \"suite\": \"205\", \"address\": \"734 Benton Ranch Apt. 146\\nRodriguezview, WY 06071-3226\", \"postcode\": \"45782\"}',2,'2019-06-28 09:50:08','2019-06-28 09:50:08');
/*!40000 ALTER TABLE `customers` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2019-06-28 10:43:07
```

Note: I've read the #86 and I'm sure that they are totally unrelated issues.

**Comment by korvinod** [comment] 2019-08-29 03:36
The same situation with the field "mediumblob"

**Comment by RoastVeg** [comment] 2019-10-11 11:33
I have created an appropriate libgda issue [here](https://gitlab.gnome.org/GNOME/libgda/issues/200)

**Comment by Alecaddd** [comment] 2020-04-12 21:47
Closing this as this is a duplicate of #86

**Closed by Alecaddd** 2020-04-12 21:47 UTC
Labels: duplicate
