### ISSUE TITLE
Allow copying fields in query results

### ISSUE THREAD

**Issue by btkostner** [Alecaddd/sequeler#138] opened 2018-08-01 16:08 UTC
Right now when you run a query you get a row of results, but you can not select any of the returned data. We should allow highlighting and right clicking data so people can easily copy it.

**Comment by Alecaddd** [comment] 2018-08-02 18:42
Yup, this feature is currently in development.
Also, I'm closing this as it's a duplicate of #71

**Closed by Alecaddd** 2018-08-02 18:42 UTC

**Comment by btkostner** [comment] 2018-08-02 18:51
woops, my bad
