### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by borjoscar** [Alecaddd/sequeler#45] opened 2017-10-20 20:53 UTC
When I try to install the app in the AppCenter, it appears a window showing this:

![captura realizada el 2017-10-20 22 52 11](https://user-images.githubusercontent.com/28791119/31841325-5aeeac18-b5e9-11e7-8421-f96c093d2726.png)

**Comment by ar0ra1** [comment] 2017-10-20 20:59
try 
sudo apt-get install libgda-5.0
and then install

**Comment by Alecaddd** [comment] 2017-10-20 21:07
argh, I can't seem to find a solution for these damn libraries.
anyway, you can solve it by installing these missing dependencies:

`sudo apt-get install libgda-5.0-mysql`
`sudo apt-get install libgda-5.0-postgresql`

**Comment by borjoscar** [comment] 2017-10-20 21:10
I have tried both commands, the first one says that I have already installed it and with its last version.
The second one says that the package can't be found.

**Comment by ar0ra1** [comment] 2017-10-20 21:16
its `sudo apt-get install libgda-5.0-postgres`

**Comment by borjoscar** [comment] 2017-10-20 21:17
Now it says that it is already installed and with its last version.

**Comment by borjoscar** [comment] 2017-10-20 21:18
Both packages are in the version (5.2.4-1ubuntu1).

**Comment by Alecaddd** [comment] 2017-10-20 21:30
I'll try on a fresh install of elementary and see what's going on.
I can quickly remove those dependencies on install and release a patch, so at least you can complete the installation from the AppCenter, but probably you won't be able to connect to any database.

**Comment by borjoscar** [comment] 2017-10-20 21:43
If it helps you, see this capture:

![screenshot from 2017-10-20 23 37 09](https://user-images.githubusercontent.com/28791119/31842828-4e2d9096-b5f0-11e7-97c2-4c821dfc02a8.png)

**Comment by ar0ra1** [comment] 2017-10-20 22:02
just for my satisfaction can you do this ? :P
`sudo apt-get install libgda-5.0*`
and try to install ?

**Comment by borjoscar** [comment] 2017-10-20 22:17
Of course!

I have tried again to install the app but it throws the same window. Here is the output of the console for your command:

![screenshot from 2017-10-21 00 14 19](https://user-images.githubusercontent.com/28791119/31843759-01a3a0da-b5f5-11e7-9d6a-be0b09f85969.png)

**Comment by Alecaddd** [comment] 2017-10-20 22:19
Confirmed, it's a wrong declaration in the Dependencies of the debian install.
I just pushed a fixed version to the AppCenter, hopefully, it'll be available soon.
Sorry about that.

**Comment by borjoscar** [comment] 2017-10-20 22:21
No problem, here we are to help!

**Comment by ar0ra1** [comment] 2017-10-20 22:22
@Alecaddd did you mean you wrote 
> libgda-mysql-5.0

instead of 

> libgda-5.0-mysql 

?

**Comment by Alecaddd** [comment] 2017-10-20 22:30
Exactly.
The problem is, the actual file that gets required is called `libgda-mysql-5.0.h`
but the library is called `libgda-5.0-mysql`

I'm having issues with the LibGda since day 1, it's a bit of a messed up library, with missing dependencies and UI library partially included but not properly referenced by the package.

No wonder it doesn't really exist a native SQL client for Linux, with this :hankey: library :stuck_out_tongue: 

And of course, the debian built passes and all the tests don't return any error while compiling.

Thank you so much, both of you, for your help.

**Comment by andbuitra** [comment] 2017-10-20 22:55
I just saw this app on the AppCenter and it was really interesting. Hopefully we could install it properly!

Thank you for your work, dev. Really appreciated.

**Comment by Alecaddd** [comment] 2017-10-21 19:00
@borjoscar @andbuitra

just released an updated version that should work.
let me know

**Comment by borjoscar** [comment] 2017-10-21 19:19
Installed and working perfectly. Thank you!

**Comment by Alecaddd** [comment] 2017-10-21 19:20
SHABAMMM :fire::fireworks:

**Closed** 2017-10-21 19:46 UTC
