### ISSUE TITLE
JSON Field Error

### ISSUE THREAD

**Issue by rushsteve1** [Alecaddd/sequeler#128] opened 2018-07-13 13:08 UTC
Attempting to view the "Content" tab of a table with a JSON field causes the following error:
```
Using unsupported buffer type: 245  (parameter: 6)
```
Where `parameter: 6` is the index of the column that is JSON type.

Database: mysql Ver 14.14 Distrib 5.7.2.2
Sequeler: 5.7 (from Flathub)
Distro: Ubuntu 18.04

**Comment by Alecaddd** [comment] 2018-07-17 04:49
Closing as this is a known issue of `LibGDA` and a duplicate of #86

**Closed by Alecaddd** 2018-07-17 04:49 UTC
